### ISSUE TITLE
Issue List

### ISSUE THREAD

**Issue by gilwoong** [kookmin-sw/capstone-2020-23#64]
#### 이슈리스트

- [x] 소팅 이슈

  미구현 추측

- [x] 검색 이슈

  미구현 추측

- [x] 공유 도감 저장 후 삭제 이슈

  삭제 기능 에러 및 삭제 시도후 저장 일체 안됌

- [ ] 공유 도감 돋보기 버튼 비 활성 이슈

- [x] 디테일에서 삭제후 도감추가 안뜨는 문제

- [x] 간헐적 검색에러

  이미지 뷰 관련 에러로 추측

**Comment by gilwoong** [comment]
1. 소팅은 길웅.
2. 검색은 준권이가. 
3. 해결.
4. 정현이.
5. 뒤로가기 이슈 해결
6. 보류

**Comment by script-brew** [comment]
검색 구현 완료

**Comment by script-brew** [comment]
공유 도감 돋보기 버튼 비활성 이슈 해결 x -> 원인을 찾을 수 없음
