### ISSUE TITLE
How to apply Android Studio Material Design.

### ISSUE THREAD

**Issue by labiss96** [kookmin-sw/capstone-2020-23#7]
> Material Design은 **Android API 21**(롤리팝) 이상에서만 적용 가능.

1. App 레벨의 gradle 파일에 dependencies 추가 [Sync now]

    ``` implementation 'com.google.android.material:material:1.1.0' ```
    > version은 appcompat의 version과 통일.

2. Material Theme 적용.
  - AndroidManifest.xml 파일에서 초기값을 사용되는 AppTheme를 변경해주어야 한다.
 - styles.xml

    ``` parent="Theme.AppCompat.Light.DarkActionBar" ```

     위 코드를 하단의 코드로 재작성

    ``` parent="Theme.MaterialComponents.Light.DarkActionBar" ```

3. 이후 사용되는 View(Button, Radio 등)는 **Material Design**이 적용됨

**Comment by maengsanha** [comment]
Close issue cause it's resolved.
